name: Docker login

on:
  push:
    branches: master
    tags:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: docker build csharp
      run: |
        docker build ./c# -t keshavbyri/csharp:1.0.0
        
    - name: docker push
      run: |
        docker push keshavbyri/csharp:1.0.0
